# Generated by Django 3.1.2 on 2020-10-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=80, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='pixel',
            name='Category',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pixel',
            name='Location',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='pixel',
            name='pud_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='pixel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='summary',
            field=models.CharField(default='', max_length=200),
        ),
    ]
