# Generated by Django 3.1.2 on 2020-10-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0002_auto_20201013_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pixel',
            name='Category',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='Location',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='summary',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pixel',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
